# Data Preprocessing Tools

Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing csv file

In [ ]:
! gdown --id 1chC4N9VHHDhrnWsA4mu02-JsZRD_G7JQ

/usr/local/lib/python3.10/dist-packages/gdown/__main__.py:132: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1chC4N9VHHDhrnWsA4mu02-JsZRD_G7JQ
To: /content/Data.csv
100% 226/226 [00:00<00:00, 916kB/s]


Importing the dataset

In [ ]:
#Creating DataFrame named dataset
dataset = pd.read_csv('Data.csv')
# x should contain all the independent values and y the dependent values

# Matrix feature X

X = dataset.iloc[:, :-1].values
# iloc gives the index ie row and column
# Here we are taking all rows and all columns except the last col ie dependent one (-1 represents last column in python)
# The lower bound is included and the upper bound like -1 is not included.

y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


Taking care of missing data

In [ ]:
# We will replace the missing salary by the average of all salaries

In [ ]:
from sklearn.impute import SimpleImputer

# SimpleImputer is a class and imputer is an object
# The argument says we need to replace the missing values ie nan values with mean
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# Fit the imputer on the DataFrame
# We apply this in cols with age and salary ie 1 and 2 thus in range we take 1:3 as lower bound is included but upper bound is not
imputer.fit(X[:, 1:3])

# Apply the transform to the DataFrame
# Since it creates a new copy of the set thus we update using assignment operator
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Encoding Categorical Data

In [ ]:
# In the country column we have 3 different countries in total
# Thus we'll turn this country column into 3 columns

# This technique is called one hot encoding
# It involves creating binary vectors for each of the countries

Encoding the Independent Variable

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# 1st argument specifies what kind of transformation we want and the index of those cols
# 2nd argument specifies remainder (other cols which we want to keep but as it is)
# passthrough is a codename means we want to keep those columns also which won't be one hot encoded
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])] , remainder='passthrough')

# Connecting it to matrix feature X (this time no need to do 2 steps ie fit and then transform but use fit_transform method which does both)
# X must be a numpy array as in future models will require those thus we use np.array
X = np.array(ct.fit_transform(X))

# Can also implement like below:
# Identify the categorical data
# categorical_data = ['Sex', 'Embarked', 'Pclass']

# Implement an instance of the ColumnTransformer class
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), categorical_data)], remainder='passthrough')

In [ ]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


Encode dependent variable

In [ ]:
from sklearn.preprocessing import LabelEncoder

# we'll pass nothing in () as it is clear we have only one vector
le = LabelEncoder()

# We don't need to take numpy array as it is not required as input in ML Models
y = le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


Splitting the dataset into Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split

# The format of variables is such that it would be expected by ML Models
# random_state = 1 - so that the split is fixed and not random
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 1)

In [ ]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

# Fit method will compute mean & standard deviation of each of the features
# Tranform method will apply the standardization formula
# fit_transform combines both of the above
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])

# The test set is meant to simulate unseen data. When you scale the test data, you should not use fit_transform because it would compute a new mean and standard deviation specifically for the test set
X_test[:, 3:] = sc. transform(X_test[:, 3:])

In [ ]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
